spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: ${BUCKET_NAME}

replicate:
  api:
    token: ${REPLICATE_SECRET}

openai:
  api-key: ${OPENAI_API_KEY}

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

# swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# server health check
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  health:
    db:
      enabled: true

firebase:
  credentials: ${FIREBASE_CREDENTIAL_PATH}